### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/minecraft-whac-a-block-game#3]
- [ ] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by lauraclay** [comment]
Don't think this one needs the remaining ymls...

**Comment by jrobinson-uk** [comment]
Updated the Worksheet to include a "What's next?" heading. Just waiting for a cover.png now
