### ISSUE TITLE
Whack events not being raised

### ISSUE THREAD

**Issue by marknadig** [raspberrypilearning/minecraft-whac-a-block-game#4]
I followed the tutorial on the site and found that the 3x3 board was correctly rendered and the glow blocks randomly show up. However, it seemed the whack events weren't firing. So, I assumed mistyped something and copied the code from here and still... whacking the glow blocks will destroy them, but it isn't registering the event, replacing the glowstone with stone. It just destroys the glow stone.

I fiddled the code - putting a mc.postToChat("ouch") at the top of the events for loop and confirmed, no "ouch" being displayed. Seems I'm not getting any events from mc.events.pollBlockHits()

Any idea what's up w/ my environment? This is a new RBPi2 with fresh raspbian and did apt-get update/upgrade.

**Comment by MissPhilbin** [comment]
@martinohanlon any ideas?

**Comment by martinohanlon** [comment]
Can I just check....

Are you 'right' clicking blocks while holding a sword? You hit a block by right clicking, left click destroys blocks and 'for some reason' you have to be holding a sword.

**Comment by marknadig** [comment]
:/  I'm a noob. Yup, was left clicking. Thanks for following up.
