### ISSUE TITLE
Game running under RPi2

### ISSUE THREAD

**Issue by mikefromd** [raspberrypilearning/minecraft-whac-a-block-game#5]
Hello,
I coded the great game on a RPi2 with the most recent NOOB and updates, but there seems to be a problem with pollBlockHits().
The blocks are not switched from glowing to normal, and also the "points" variable never adds points.

It looks as the method used with the for iterator is not returning values.

Where can I look for debugging information to sort out my problem?
Thank you.

**Comment by bennuttall** [comment]
@martinohanlon?

**Comment by martinohanlon** [comment]
@mikefromd Could you confirm when you are 'hitting' a block you are hold a sword and using the right mouse button, not the left?

**Comment by mikefromd** [comment]
Dear Martin,

I've got it, sorry.
Yes, I used the sword, but I clicked on the left mouse button, not the right one.
Everything is working fine.

Thank you for this easy to implement, but still engaging game.

With best regards,
Michael
